# Cuda 9.0
name: gan_pytorch
channels:
- anaconda
- defaults
- pytorch
dependencies:
- tensorflow=1.11.0
- torchvision=0.2.1
- pytest=3.9.3
- python=3.6
- pytorch=0.4
- pip:
  - face_alignment
  - opencv-python-headless
  - tensorboardX
  - tqdm
  - pylint
