# Network
model: XGAN

# Dataset
dataset_mode: image2image
dataA: data/demo/faces
dataB: data/demo/faces
load_size: 64
crop_size: 64
serial_batches: False

# Environment
num_threads: 0
gpu_ids: -1

# Train process
checkpoints_dir: ./checkpoints/demo
print_freq: 10
display_freq: 10
save_epoch_freq: 1
niter: 10
niter_decay: 10 
continue_train: False
epoch: 0
epoch_count: 1

# Major hyper parameters
name: xgan
batch_size: 8
lr: 0.0001
beta1: 0.5
lambda_dann: 1
lambda_sem: 1
lambda_rec: 1

# Minor hyper parameters
init_type: normal
init_gain: 0.02
noise_level: 0
flip_prob: 0
