# Network
model: WGANGP
ngf: 128
ndf: 128

# Dataset
dataset_mode: latent2image
dataroot: data/demo/faces
load_size: 64
crop_size: 64
latent_size: 100
serial_batches: False

# Environment
num_threads: 0
gpu_ids: -1

# Train process
checkpoints_dir: ./checkpoints/demo
print_freq: 10
display_freq: 10
save_epoch_freq: 1
epoch: 10
epoch_decay: 10 
continue_train: False
load_epoch: 0
epoch_count: 1

# Major hyper parameters
name: dcgan_gp
batch_size: 8
lr: 0.0001
beta1: 0
lambda_gp: 10
every_g: 5
every_d: 1

# Minor hyper parameters
init_type: normal
init_gain: 0.02
noise_level: 0
flip_prob: 0
