# Network
model: VAEGAN
ngf: 32
ndf: 64

# Dataset
dataset_mode: image
dataroot: data/demo/faces
load_size: 64
crop_size: 64
latent_size: 256
serial_batches: False

# Environment
num_threads: 0
gpu_ids: -1

# Train process
checkpoints_dir: ./checkpoints/demo
print_freq: 10
display_freq: 10
save_epoch_freq: 1
epoch: 10
epoch_decay: 10 
continue_train: False
load_epoch: 0
epoch_count: 1

# Major hyper parameters
name: vaegan
batch_size: 8
lr: 0.0002
beta1: 0.5
lambda_kl: 0.01
lambda_idt: 1

# Minor hyper parameters
init_type: xavier
init_gain: 0.02
