# Network
model: VAE
ngf: 32
ndf: 32

# Dataset
dataset_mode: latent2image
dataroot: data/anime/faces
load_size: 64
crop_size: 64
latent_size: 256
serial_batches: False

# Train process
checkpoints_dir: ./checkpoints/anime_ae
num_threads: 0
gpu_ids: 0
print_freq: 200
display_freq: 500
save_epoch_freq: 5
niter: 50
niter_decay: 50 
continue_train: False
epoch: 0
epoch_count: 1

# Major hyper parameters
name: lr2e-4_b64
batch_size: 64
lr: 0.0002
beta1: 0.5
lambda_kl: 0.1
init_type: normal
init_gain: 0.02
