# Network
model: ACGANGP
ngf: 128
ndf: 128

# Dataset
dataset_mode: class2image
dataroot: data/anime_label/
load_size: 64
crop_size: 64
latent_size: 100
serial_batches: False

# Train process
checkpoints_dir: ./checkpoints/anime_label
num_threads: 0
gpu_ids: 0
print_freq: 10
display_freq: 10
save_epoch_freq: 1
niter: 50
niter_decay: 50
continue_train: False
epoch: 0
epoch_count: 1

# Major hyper parameters
name: acgangp_lr1e-4_c5_b64
batch_size: 64
lr: 0.0001
beta1: 0
init_type: normal
init_gain: 0.02
noise_level: 0
flip_prob: 0
lambda_class: 5
lambda_gp: 10
every_g: 5
