# Network
model: ACGAN
ngf: 128
ndf: 128

# Dataset
dataset_mode: class2image
dataroot: data/anime/faces
load_size: 64
crop_size: 64
latent_size: 100
serial_batches: False

# Train process
checkpoints_dir: ./checkpoints/anime
num_threads: 0
gpu_ids: 0
print_freq: 2000
display_freq: 2000
save_epoch_freq: 10
niter: 100
niter_decay: 100 
continue_train: False
epoch: 0
epoch_count: 1

# Major hyper parameters
name: dcgan_lr0002
batch_size: 8
lr: 0.0002
beta1: 0.5
init_type: normal
init_gain: 0.02
noise_level: 0
flip_prob: 0
